name: JS SDK

on:
  push:
    branches: [main]
    paths:
      - "js/**"
      - ".github/workflows/js.yml"
  pull_request:
    paths:
      - "js/**"
      - ".github/workflows/js.yml"

defaults:
  run:
    working-directory: js

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: ["18", "20"]
    name: node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm
          cache-dependency-path: js/package-lock.json

      - run: npm ci
      - run: npm run build
      - run: npm test
